import Head from 'next/head'
import "locomotive-scroll/dist/locomotive-scroll.css"
import Placeholder from '@/components/feature/Placeholder'
import { SmoothScrollContext } from '@/contexts/SmoothScroll.context';
import { useContext, useEffect, useState } from 'react';

export default function Home() {


  const scrollContext = useContext(SmoothScrollContext);
  const [stopped, setStopped] = useState(true);
  const [progress, setProgress] = useState(0);

  function clickHandler() {
    if (stopped) {
      console.log("start")
      scrollContext.scroll?.start()
    } else {
      console.log("stop")
      scrollContext.scroll?.stop()
    }
    setStopped(!stopped)
  }

  function rightClickHandler(e) {
    console.log("right click!")
    e.preventDefault();
    scrollContext.scroll?.scrollTo(progress + window.innerHeight);
  }

  useEffect(() => {
    scrollContext.scroll?.on('scroll', ({ limit, scroll }) => {
      setProgress(scroll.y)
    })
  }, [scrollContext.scroll])

  return (
    <>
      <Head>
        <title>Next + Locomotive scroll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div data-scroll-container onClick={clickHandler} onContextMenu={rightClickHandler}>
        <div data-scroll-section>
          {Array(10).fill(0).map((element, index) => {
            return (
              <Placeholder key={index} blockIndex={index} />
            );
          })}
        </div>
      </div>

    </>
  )
}
