import Head from 'next/head'
import { SmoothScrollProvider } from "../contexts/SmoothScroll.context"
import "locomotive-scroll/dist/locomotive-scroll.css"
import Placeholder from '@/components/feature/Placeholder'
import styles from "../styles/main.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SmoothScrollProvider options={{ smooth: true }}>
        <div className={styles.scrollContainer} data-scroll-container>
          <div className={styles.scrollSection} data-scroll-section>
            {Array(10).fill(0).map((element, index) => {
              return (
                <Placeholder key={index} />
              );
            })}
          </div>
        </div>
      </SmoothScrollProvider>
    </>
  )
}
